### ISSUE TITLE
Errors when using any other color LUT modes in the fog volume

### ISSUE THREAD

**Issue by PixelDough** [pastasfuture/com.hauntedpsx.render-pipelines.psx#13]
Changing the color LUT mode to any other setting causes all the materials to go solid pink, and results in this error in the console:
![image](https://user-images.githubusercontent.com/25268968/135158056-77d377d7-eb0c-43c7-a4e7-9b6dd65b7168.png)

This happens in every single project I've tested it in. I know it was working before, but something in a recent update must have brought up an issue.

**Comment by pastasfuture** [comment]
Fixed. It landed in 1.6.0. thanks for reporting🖤
