### ISSUE TITLE
Particles using materials with Texture Filter Mode set to "N64" display incorrectly

### ISSUE THREAD

**Issue by PixelDough** [pastasfuture/com.hauntedpsx.render-pipelines.psx#17]
While using the N64 Texture Filter Mode, if I set the material to not use alpha clipping, the texture appears with no alpha at all in the particle. However, if I enable alpha clipping (or change the material to use Transparent Surface Type), they look like a strange distorted line, or don't appear at all

Without N64 mode:
![image](https://user-images.githubusercontent.com/25268968/135738392-99b7fca7-75d3-4fb7-9d38-ca47278b3bef.png)

With the N64 mode:
![image](https://user-images.githubusercontent.com/25268968/135738400-ab4965cd-9591-487e-9044-03c7b55a712c.png)

**Comment by pastasfuture** [comment]
Can you share with me a specific particle sim + material + texture that this happens for you on? I was not able to reproduce it with my own material + texture + particle sim (so probably missing something you are doing).

**Comment by pastasfuture** [comment]
I verified N64 texture filter mode works correctly on particles on master e779c1c2af4a4a1fc2b98807063cc547ea49877d at the time of writing.
