### ISSUE TITLE
Issue with Git-LFS and Unity auto-pull

### ISSUE THREAD

**Issue by boakes** [pastasfuture/com.hauntedpsx.render-pipelines.psx#2]
Probably more of an issue with Unity's builtin Package Importer, but I had to manually pull in the image files since they are being hosted with Git-LFS. 

Could possibly mention in the wiki about needing to download the image files in Runtime/RenderPipelineResources/Texture separately.

**Comment by pastasfuture** [comment]
The installation guide in the wiki has since been updated to mention the requirement of git LFS if using the git url install method. https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/wiki/Installation-Guide#installation-via-git-url-in-packagesjson-file-requires-git--git-lfs
