### ISSUE TITLE
Render Texture doesnt have any transparency 

### ISSUE THREAD

**Issue by PressFToPayRespekk** [pastasfuture/com.hauntedpsx.render-pipelines.psx#26]
I tried to give my fps weapon its own camera and use a render texture to display the weapon on top of everything but I've realized that the render textures doesn't currently have working transparency (compared to the built-in pipeline), to reproduce this effect just create 2 cameras, 1 normal one and 1 for the render texture. Then make a raw image and put the render texture to the texture field. Make sure the camera with the render texture has "Clear Flags" set to Depth only and for the culling mask make it only render one layer.

**Comment by PressFToPayRespekk** [comment]
Unity version: 2020.3.30f1

**Comment by pastasfuture** [comment]
In order for your render texture to have transparency, you need to set your Sky Volume mode to Background Color. Then on your camera, set it's Background Color variable to fully transparent (alpha 0).
