### ISSUE TITLE
Scanlines only rendered when game resolution height is greater than (rasterization res. height x 2)

### ISSUE THREAD

**Issue by kpietraszko** [pastasfuture/com.hauntedpsx.render-pipelines.psx#27]
For example, set game resolution to 720p. With Rasterization Resolution Y set to 360, you don't see scanlines. With 359, they're visible. 
Is that expected?

**Comment by pastasfuture** [comment]
Yeah - unforunately the way the CRT shader is currently written, it expects rasterization resolution to be significantly lower than output resolution for the effect to work well. I need to design a different version for getting a CRT look with rasterization resolution and output resolution at similar settings.
