### ISSUE TITLE
Wanting to outline my player

### ISSUE THREAD

**Issue by MikeRoeGames** [pastasfuture/com.hauntedpsx.render-pipelines.psx#29]
Hello, I and a friend are wanting to add a function to the psx shaders that would render an outline around the player. We have looked at normal tutorials but we are a bit stuck. Any idea how we could get this done? Basically we are wanting to edit the shaders.

**Comment by pastasfuture** [comment]
Hey, thanks for reaching out - unfortunately, writing custom shaders for HPSXRP is fairly complicated compared to the built in render pipeline (or URP or HDRP for that matter). In the future I'd love to design ways for users to more easily author their own shaders that are compatible with HPSXRP, but for now, this is outside of the scope of the project.
