### ISSUE TITLE
error CS1501: No overload for method 'SetReferenceSize' takes 3 arguments

### ISSUE THREAD

**Issue by rikocodes** [pastasfuture/com.hauntedpsx.render-pipelines.psx#31]
I got two errors when trying to install the hpsxrp in a new empty project:

Library\PackageCache\com.hauntedpsx.render-pipelines.psx@a28da49f24\Runtime\RenderPipeline\PSXCamera.cs(152,23): error CS1501: No overload for method 'SetReferenceSize' takes 3 arguments

Library\PackageCache\com.hauntedpsx.render-pipelines.psx@a28da49f24\Runtime\RenderPipeline\PSXCamera.cs(153,29): error CS1501: No overload for method 'SwapAndSetReferenceSize' takes 3 arguments

Unity version used: 2021.3.5f1

**Comment by MarkIsTheBest** [comment]
I've also recieved this error, eventually what I did to fix it was go into the forementioned script and changed the two error line into this :    RTHandles.SetReferenceSize(context.rasterizationWidth, context.rasterizationHeight);
            historyRTSystem.SwapAndSetReferenceSize(context.rasterizationWidth, context.rasterizationHeight);

**Comment by AdnanxYousuf** [comment]
It removed the errors but the Material stopped working + got few errors. Actually the project is working on Unity 2020 but if I update it to 2021 it is not working anymore.

![Uploading It didn't work.png…]()
