### ISSUE TITLE
Error regarding importing the asset!

### ISSUE THREAD

**Issue by AdnanxYousuf** [pastasfuture/com.hauntedpsx.render-pipelines.psx#33]
After importing the asset, the unity is giving me some errors mention below. How to fix it?
![Errors](https://user-images.githubusercontent.com/78865176/213926806-b6cdbd6a-7dfe-49a0-adb5-dc0bf4aa5d40.PNG)

**Comment by HeadClot** [comment]
I would check out [this](https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/issues/31) issue. It should have a fix.

**Comment by AdnanxYousuf** [comment]
It removed the errors but the Material stopped working + got few errors. Actually the project is working on Unity 2020 but if I update it to 2021 it is not working anymore.
![test](https://user-images.githubusercontent.com/78865176/215323286-357fcc45-9052-4526-835f-bd4757f46092.png)
