### ISSUE TITLE
Is it possible to change the skybox with this plugin?

### ISSUE THREAD

**Issue by CristianGOEN** [pastasfuture/com.hauntedpsx.render-pipelines.psx#34]
Hi i'm trying to set the sky volume, sky mode on and can't change my skybox material, it does nothing, is it a bug from the plugin?

**Comment by Alvarden15** [comment]
It IS possible to do that: on the Volume, add the override **Sky Volume** and change the sky mode to **Skybox**, and then you can add the Skybox texture you want.
