### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ben-forster** [pastasfuture/com.hauntedpsx.render-pipelines.psx#35]
Any signs of this coming? This render pipeline currently doesn't support Apple's M series chips as far as I can tell.

**Comment by pastasfuture** [comment]
Following up on this (sorry its been a while). I just rolled out a new version, with lots of bugfixes, including some platform ones. Unfortunately I do not have an Apple M series device to test on - would you be able to test on the latest master (commit e779c1c2af4a4a1fc2b98807063cc547ea49877d as of writing?) Would love to know if the pipeline now supports Apply M series chips!

**Comment by pastasfuture** [comment]
Closing for now, please open a new issue if you continue to experience problems on latest.
