### ISSUE TITLE
No rendering and errors in console despite reinstall, restart, and creation of global volumes with PSX quality enabled.

### ISSUE THREAD

**Issue by ThickyVEVO** [pastasfuture/com.hauntedpsx.render-pipelines.psx#40]
I've attempted to update my project to a new version of the psx render pipeline in order to use the tools that newer versions of unity provide. Unfortunately, no matter what I do, it seems to create the same error in console constantly and will not render anything, even with the proper material, pipeline asset, etc. I've tried multiple versions, from 2020.3.48f1, to 2021.3.25f1, and also 2022.2.21f1. None have worked and the console is constantly pinged with:

"MissingReferenceException: The object of type 'Texture2D' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Texture.get_width () (at <cd86b0d4df634b6a8fd612065f941dcd>:0)
HauntedPSX.RenderPipelines.PSX.Runtime.PSXRenderPipeline.PushGlobalRasterizationParameters (UnityEngine.Camera camera, UnityEngine.Rendering.CommandBuffer cmd, UnityEngine.Rendering.RTHandle rasterizationRT, System.Int32 rasterizationWidth, System.Int32 rasterizationHeight, System.Boolean hdrIsSupported) (at ./Packages/com.hauntedpsx.render-pipelines.psx-master/Runtime/RenderPipeline/PSXRenderPipeline.cs:913)
HauntedPSX.RenderPipelines.PSX.Runtime.PSXRenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Camera[] cameras) (at ./Packages/com.hauntedpsx.render-pipelines.psx-master/Runtime/RenderPipeline/PSXRenderPipeline.cs:291)
UnityEngine.Rendering.RenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at <cd86b0d4df634b6a8fd612065f941dcd>:0)
UnityEngine.Rendering.RenderPipeline.InternalRender (UnityEngine.Rendering.ScriptableRenderContext context, System.Collections.Generic.List`1[T] cameras) (at <cd86b0d4df634b6a8fd612065f941dcd>:0)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipe, System.IntPtr loopPtr, UnityEngine.Object renderRequest, Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle safety) (at <cd86b0d4df634b6a8fd612065f941dcd>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)"

**Comment by ThickyVEVO** [comment]
Also something to note, this happens in every project, I've tried making new ones in all of these versions and get the same error.

**Comment by pastasfuture** [comment]
Hi - just checking in - did you find a solution to your issue? Im curious, why did you close the issue?

**Comment by ThickyVEVO** [comment]
Yeah, I just had to reinstall git and it seemed to fix the issue. I assume
it was just I was on an outdated version because it worked with 1.6.1.
